apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: webgoat-network-policy
    namespace: webgoat
spec:
    podSelector:
        matchLabels:
            app: webgoat
    ingress:
        - from:
              - namespaceSelector:
                    matchLabels:
                        environment: production
          ports:
              - protocol: TCP
                port: 8080
    policyTypes:
        - Ingress
