---
- name: Configure WebGoat Cluster
  hosts: local
  tasks:
      - name: Create WebGoat namespace
        command: kubectl create namespace webgoat
        ignore_errors: true

      - name: Apply Resource Quota for WebGoat
        command: kubectl apply -f resource_quota.yml
        ignore_errors: true

      - name: Apply Network Policy for WebGoat
        command: kubectl apply -f network_policy.yml
        ignore_errors: true

      - name: Create Service Account for WebGoat
        command: kubectl create serviceaccount webgoat-sa -n webgoat
        ignore_errors: true

      - name: Apply Deployment for WebGoat
        command: kubectl apply -f deployment.yml
        ignore_errors: true

      - name: Apply Service for WebGoat
        command: kubectl apply -f service_account.yml
        ignore_errors: true

      - name: Create Monitoring Namespace
        command: kubectl create namespace monitoring
        ignore_errors: true
    
      - name: Create Service Account for Prometheus
        command: kubectl create serviceaccount prometheus-sa -n monitoring
        ignore_errors: true
