---
- name: Configure WebGoat Cluster
  hosts: webgoat
  tasks:
      - name: Create WebGoat namespace
        command: kubectl create namespace webgoat
        ignore_errors: true

      - name: Apply Resource Quota for WebGoat
        command: kubectl apply -f resource_quota.yml
        ignore_errors: true

      - name: Create Service Account for WebGoat
        command: kubectl create serviceaccount webgoat-sa -n webgoat
        ignore_errors: true

      - name: Apply Deployment for WebGoat
        command: kubectl apply -f WebGoat/ansible/playbooks/deployment.yml
        ignore_errors: true

      - name: Apply Service for WebGoat
        command: kubectl apply -f WebGoat/ansible/playbooks/service_account.yml
        ignore_errors: true
