global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webgoat'
    metrics_path: '/WebGoat/actuator/prometheus'
    static_configs:
      - targets: ['webgoat-service.webgoat.svc.cluster.local:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kube-state-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']