apiVersion: v1
kind: ResourceQuota
metadata:
    name: webgoat-quota
    namespace: webgoat
spec:
    hard:
        requests.cpu: "500m"
        requests.memory: "256Mi"
        limits.cpu: "500m"
        limits.memory: "512Mi"
        pods: "10"
