apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
  namespace: webgoat
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31051  
  selector:
    app: webgoat
