name: Discord Notifications

on:
  workflow_run:
    workflows: ["SonarQube Analysis", "Docker Build, Security Scan, and Publish"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            Security Tests Status: 
            **Workflow:** ${{ github.event.workflow_run.name }}
            **Status:** ${{ github.event.workflow_run.conclusion }}
            **Branch:** ${{ github.event.workflow_run.head_branch }}
            **Commit:** ${{ github.event.workflow_run.head_commit.message }}
