name: Build and Deploy WebGoat

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      # Step 3: Build the application
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          ls target  # Verify the target directory contents

      # Step 4: Build and push Docker image
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webgoat:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/webgoat:latest

      # Step 5: Deploy to Kubernetes (optional)
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl get pods
          kubectl get services
