name: Webgoat deployment test

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: 'yelghom/WebGoat'
        path: 'WebGoat'

    - name: List files in ansible directory
      run: |
        ls -al WebGoat/ansible

    
    - name: Set up SSH agent
      uses: actions/checkout@v2
      with:
        ssh-keys: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone Repository
      run: |
        git clone https://github.com/yelghom/WebGoat.git /home/runner/webgoat-repo

    # Set up Minikube
    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start --driver=docker

    # Set up kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
        sudo chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        
    - name: Deploy with Ansible on Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@172.190.64.130 << 'EOF'
          cd WebGoat/ansible/playbooks || exit
          ansible-playbook configure_cluster.yml
        EOF
