name: Webgoat deployment test

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: 'yelghom/WebGoat'
        path: 'WebGoat'

    - name: List files in ansible directory
      run: |
        ls -al WebGoat/ansible
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        
    - name: Deploy with Ansible on Azure VM
      run: |
       ansible-playbook -i WebGoat/ansible/playbooks/hosts WebGoat/ansible/playbooks/configure_cluster.yml

    - name: Show webgoat service url
      run: |
        echo "Webgoat Service"
        echo "http://20.237.30.13/WebGoat/login"
