name: WebGoat Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH agent
        uses: actions/checkout@v2
        with:
          ssh-keys: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Update APT and Install Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y default-jdk git unzip

      - name: Deploy WebGoat with Ansible
        run: |
          cd WebGoat/ansible/playbooks
          ansible-playbook -i hosts configure_cluster.yml
