name: WebGoat Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'yelghom/WebGoat'
          path: 'WebGoat'
      

      - name: List files in ansible directory
        run: |
          ls -al WebGoat/ansible
        
      - name: Set up SSH agent
        uses: actions/checkout@v2
        with:
          ssh-keys: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Update APT and Install Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y default-jdk git unzip

      - name: Navigate to playbooks directory
        run: |
          cd WebGoat/ansible/playbooks

      - name: Deploy with Ansible
        run: |
          ansible-playbook -i hosts configure_cluster.yml

      # - name: Deploy WebGoat with Ansible
      #   run: |
      #     cd WebGoat/ansible/playbooks
      #     ansible-playbook -i hosts configure_cluster.yml
